language: node_js
services:
  - docker

before_install:
  - docker bulid -t thianqiwee00/reactapp -f Dockerfile.dev .

script: #start of our build
  - docker run thianqiwee00/reactapp npm run test -- --coverage
  